import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class UtilService {
  constructor() {}

  langIsEs(): boolean {
    return localStorage.getItem('lang') === 'es';
  }

  setLang(lang: 'es' | 'en'): void {
    localStorage.setItem('lang', lang);
  }

  getIconForSkill(skill: string): string {
    const iconMap: { [key: string]: string } = {
      'Angular': 'simpleAngular',
      'Angular Standalone': 'simpleAngular',
      'RxJs': 'simpleReactivex',
      'NgRx (Redux)': 'simpleNgrx',
      'NgRx': 'simpleNgrx',
      'Redux': 'simpleRedux',
      'TypeScript': 'simpleTypescript',
      'JavaScript': 'simpleJavascript',
      'Git': 'simpleGit',
      'Jasmine/Karma': 'simpleJasmine',
      'Jasmine': 'simpleJasmine',
      'Karma': 'simpleJasmine',
      'Cypress': 'simpleCypress',
      'API REST': 'simplePostman',
      'REST API': 'simplePostman',
      'Ionic': 'simpleIonic',
      'Capacitor': 'simpleCapacitor',
      'Cordova': 'simpleApachecordova',
      'Stencil.js': 'simpleStencil',
      'JSON': 'simpleJson',
      'HTML/CSS/SCSS': 'simpleHtml5',
      'HTML/SCSS': 'simpleHtml5',
      'HTML/CSS': 'simpleHtml5',
      'HTML': 'simpleHtml5',
      'CSS': 'simpleCss',
      'jQuery': 'simpleJquery',
      'React': 'simpleReact',
      'React Context': 'simpleReact',
      'React Hooks': 'simpleReact',
      'Keycloak': 'simpleKeycloak',
      'Web Components': 'simpleWebcomponentsdotorg',
      'Jira/Confluence': 'simpleAtlassian',
      'SCRUM': 'simpleJira',
      'MySQL': 'simpleMysql',
      'Jenkins': 'simpleJenkins',
      'Android': 'simpleAndroid',
      'Android/iOS': 'simpleAndroid',
      'Ionic Trapeze': 'simpleIonic',
      'Arquitecture': 'ionConstruct',
      'SOLID': 'ionConstruct',
      'iOS/Swift': 'simpleIos',
      'Bootstrap': 'simpleBootstrap',
      'Node.js': 'simpleNodedotjs',
      'Express.js': 'simpleExpress',
      'Jest': 'simpleJest',
      'Styled Components': 'simpleStyledcomponents',
      'Styled-icons': 'simpleStyledcomponents',
      'PrimeNG': 'simplePrimeng',
      'Open AI (Inteligencia artificial) GPT 3+, DALL-E': 'simpleOpenai',
      'Open AI (Artificial Intelligence) GPT 3+, DALL-E': 'simpleOpenai',
      'OpenAI API': 'simpleOpenai',
      'Inteligencia artificial': 'simpleOpenai',
      'Design Patterns': 'ionConstruct',
      'Design Tools (Figma, GNU)': 'simpleFigma',
      'e2e & Cypress': 'simpleCypress',
      'Angular Material': 'simpleAngular',
      'ngx-ever-components': 'simpleAngular',
      'MapBox': 'simpleMapbox',
      'Responsive': 'ionPhonePortrait',
      'AOS (Animation on Scroll)': 'simpleScrollreveal',
      'ng-icons': 'simpleAngular',
      'localStorage': 'ionSave',
      'SCSS': 'simpleSass'
    };

    return iconMap[skill] || '';
  }

  getIconColorForSkill(skill: string): string {
    const colorMap: { [key: string]: string } = {
      'Angular': '#DD0031',
      'Angular Standalone': '#DD0031',
      'RxJs': '#B7178C',
      'NgRx (Redux)': '#BA2BD2',
      'NgRx': '#BA2BD2',
      'Redux': '#764ABC',
      'TypeScript': '#3178C6',
      'JavaScript': '#F7DF1E',
      'Git': '#F05032',
      'Jasmine/Karma': '#8A4182',
      'Jasmine': '#8A4182',
      'Karma': '#42B883',
      'Cypress': '#17202C',
      'API REST': '#FF6C37',
      'REST API': '#FF6C37',
      'Ionic': '#3880FF',
      'Capacitor': '#119EFF',
      'Cordova': '#E8E8E8',
      'Stencil.js': '#4C48FF',
      'JSON': '#FFFFFF',
      'HTML/CSS/SCSS': '#E34F26',
      'HTML/SCSS': '#E34F26',
      'HTML/CSS': '#E34F26',
      'HTML': '#E34F26',
      'CSS': '#1572B6',
      'jQuery': '#0769AD',
      'React': '#61DAFB',
      'React Hooks': '#61DAFB',
      'React Context': '#61DAFB',
      'Keycloak': '#00BFFF',
      'Web Components': '#29B6F6',
      'Jira/Confluence': '#0052CC',
      'SCRUM': '#0052CC',
      'MySQL': '#4479A1',
      'Jenkins': '#D24939',
      'Android': '#3DDC84',
      'Android/iOS': '#3DDC84',
      'Ionic Trapeze': '#3880FF',
      'Arquitecture': '#FFFFFF',
      'SOLID': '#FFFFFF',
      'iOS/Swift': '#F05138',
      'Bootstrap': '#7952B3',
      'Node.js': '#339933',
      'Express.js': '#FFFFFF',
      'Jest': '#C21325',
      'Styled Components': '#DB7093',
      'Styled-icons': '#DB7093',
      'PrimeNG': '#DD0031',
      'Open AI (Inteligencia artificial) GPT 3+, DALL-E': '#00A67E',
      'Open AI (Artificial Intelligence) GPT 3+, DALL-E': '#00A67E',
      'OpenAI API': '#00A67E',
      'Inteligencia artificial': '#00A67E',
      'Design Patterns': '#FFFFFF',
      'Design Tools (Figma, GNU)': '#F24E1E',
      'e2e & Cypress': '#00bf88',
      'Angular Material': '#DD0031',
      'ngx-ever-components': '#DD0031',
      'MapBox': '#4264FB',
      'Responsive': '#FFFFFF',
      'AOS (Animation on Scroll)': '#FF6C37',
      'ng-icons': '#DD0031',
      'localStorage': '#F7DF1E',
      'SCSS': '#CC6699'
    };
    return colorMap[skill] || 'var(--green)';
  }
}
