import { bootstrapApplication } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';
import { importProvidersFrom } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import { AppComponent } from './app/app.component';
import { appRoutes } from './app/app.routes';
import { NgIconsModule } from '@ng-icons/core';
import {
  ionChevronUp,
  ionChevronDown,
  ionClose,
  ionDownload,
  ionLogoLinkedin,
  ionMail,
  ionPhonePortrait,
  ionConstruct,
  ionSave,
} from '@ng-icons/ionicons';
import {
  simpleAngular,
  simpleReactivex,
  simpleRedux,
  simpleTypescript,
  simpleJavascript,
  simpleGit,
  simpleJasmine,
  simpleIonic,
  simpleCapacitor,
  simpleApachecordova,
  simpleJson,
  simpleHtml5,
  simpleCss,
  simpleSass,
  simpleJquery,
  simpleReact,
  simpleKeycloak,
  simpleWebcomponentsdotorg,
  simpleJira,
  simpleConfluence,
  simpleMysql,
  simpleJenkins,
  simpleAndroid,
  simpleIos,
  simpleSwift,
  simpleBootstrap,
  simpleNodedotjs,
  simpleExpress,
  simpleJest,
  simpleStyledcomponents,
  simplePrimeng,
  simpleOpenai,
  simpleSpringboot,
  simpleCypress,
  simpleNgrx,
  simpleFigma,
  simplePostman,
  simpleMapbox,
  simpleStencil,
  simpleGoogle,
  simpleScrollreveal,
  simpleAtlassian,
} from '@ng-icons/simple-icons';

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(appRoutes),
    provideAnimations(),
    importProvidersFrom(
      HttpClientModule,
      NgIconsModule.withIcons({
        ionLogoLinkedin,
        ionMail,
        ionClose,
        ionDownload,
        ionChevronUp,
        ionChevronDown,
        ionSave,
        simpleAngular,
        simpleReactivex,
        simpleRedux,
        simpleTypescript,
        simpleJavascript,
        simpleGit,
        simpleJasmine,
        simpleIonic,
        simpleCapacitor,
        simpleApachecordova,
        simpleJson,
        simpleHtml5,
        simpleCss,
        simpleSass,
        simpleJquery,
        simpleReact,
        simpleKeycloak,
        simpleWebcomponentsdotorg,
        simpleJira,
        simpleConfluence,
        simpleMysql,
        simpleJenkins,
        simpleAndroid,
        simpleIos,
        simpleSwift,
        simpleBootstrap,
        simpleNodedotjs,
        simpleExpress,
        simpleJest,
        simpleStyledcomponents,
        simplePrimeng,
        simpleOpenai,
        simpleSpringboot,
        simpleCypress,
        simpleNgrx,
        simpleFigma,
        simplePostman,
        simpleMapbox,
        simpleStencil,
        simpleGoogle,
        ionPhonePortrait,
        ionConstruct,
        simpleScrollreveal,
        simpleAtlassian,
      })
    ),
  ],
}).catch((err) => console.error(err));
